name: CCDA parsing with Spark
run-name: ${{ github.actor }} is doing a test run of the CCDA parsing
on: workflow_dispatch
jobs:
    learn-scripting:
        runs-on: ubuntu-latest
        steps:
          - name: test ssh to github
            shell: bash
            run: |
              ssh -T git@github.com  
          - name: start agent and add key direclty
            shell: bash
            run: |
              eval $(ssh-agent -s)
              echo "${{ secrets.GH_WF }}" | ssh-add -
          - name: setenv and start agent
            shell: bash
            run: |
              eval $(ssh-agent -s)
              echo "SSH_PUBLIC_KEY=$( echo "${{ secrets.GH_WF }}" | cut -c 1-70) " >> "$GITHUB_ENV"
          - name: part 2
            shell: bash
            run: |
              echo "$SSH_PUBLIC_KEY" | ssh-add -
          - name: get data
            uses: actions/checkout@main
            with:
                repository: chrisroederucdenver/CCDA_OMOP_Private
                path: './ref_data'
                ref: main
          - name: bogus
            shell: bash
            run: |
              echo "bugos"
    learn-scripting-2:
        runs-on: ubuntu-latest
        steps:
          - name: setup key
            uses: webfactory/ssh-agent@v0.7.0
            with:
              ssh-private-key: ${{ secrets.GH_WF }}
          - name: get data
            uses: actions/checkout@main
            with:
                repository: chrisroederucdenver/CCDA_OMOP_Private
                path: './ref_data'
                ref: main
          - name: bogus
            shell: bash
            run: |
              echo "bugos"
    Run-main:
        runs-on: ubuntu-latest
        steps:
          - name: Check out repository code
            uses: actions/checkout@v4
            with:
              ref: main
          - name: show starting files 
            shell: bash
            run: |
                ls
          - name: get data
            uses: actions/checkout@main
            with:
                repository: chrisroederucdenver/CCDA_OMOP_Private
                path: './ref_data'
                ref: main
          - name: show after files 
            shell: bash
            run: |
                ls
          - name: show ref_data files 
            shell: bash
            run: |
                ls ref_data
          - name: show current working directory 
            shell: bash
            run: |
                pwd
          - name: Install pyspark
            run: |
                pip install pyspark
          - name: run main.py 
            run: |
                python3 main.py -n=2
    Lint-Flake8:
        runs-on: ubuntu-latest
        steps:
          - name: Install linters
            run: |
                pip install flake8
          - name: Install pyspark
            run: |
                pip install pyspark
          - name: Check out repository code
            uses: actions/checkout@v4
            with:
              ref: main
          - name: Lint with flake8
            run: |
                flake8 *.py --count --select=E9,F36,F92 --show-source --max-line-length=100 --statistics
                flake8 *.py  --count --max-complexity=10 --max-line-length=100 --statistics
    Lint-Pylint:
        runs-on: ubuntu-latest
        steps:
          - name: Install linters
            run: |
                pip install pylint
          - name: Install pyspark
            run: |
                pip install pyspark
          - name: Check out repository code
            uses: actions/checkout@v4
            with:
              ref: main
          - name: Lint with Pylint
            run: |
                pylint --max-locals=25  *.py

