name: CCDA parsing with Spark
run-name: ${{ github.actor }} is doing a test run of the CCDA parsing
on: [push, workflow_dispatch]
jobs:
    Run-prototype-2:
        runs-on: ubuntu-latest
        steps:
          - name: Check out repository code
            uses: actions/checkout@v4
            with:
              ref: main
          - name: change directory to prototype_2
            shell: bash
            run: |
                mkdir output
                ls
                cd prototype_2
                pwd
                ls
          - name: Install pandas
            run: |
                pip install pandas
                pip install lxml
          - name: Run parse.py
            run: |
                cd prototype_2
                python3 parse.py
          - name: Run data_driven_parse.py
            run: |
                python3 -m prototype_2.data_driven_parse
          - name: Run layer_datsets.py
            run: |
                python3 -m prototype_2.layer_datasets
          - name: compare output
            run: |
                bin/compare_correct.sh
