name: Prototype 2
run-name: ${{ github.actor }} is testing Prototype 2
on: [push, workflow_dispatch]
jobs:
    Run-prototype-2:
        runs-on: ubuntu-latest
        steps:
          - name: Check out repository code
            uses: actions/checkout@v4
            with:
              ref: main
          - name: Check out data
            run: |
              eval $(ssh-agent -s)
              echo "${{ secrets.GH_WF }}" | ssh-add -
              ssh -T git@github.com   || true
              git clone git@github.com:chrisroederucdenver/CCDA-data.git
          - name: housekeeping,  change directory to prototype_2
            shell: bash
            run: |
                pwd
                ln -s CCDA-data/resources .
                mkdir output
                mkdir logs
                echo "-- ls -lht resources"
                ls resources
          - name: Install pandas
            run: |
                pip install pandas
                pip install lxml
          - name: Run data_driven_parse.py
            run: |
                python3 -m prototype_2.data_driven_parse -d resources
          - name: Run layer_datsets.py
            run: |
                python3 -m prototype_2.layer_datasets -d resources
          - name: compare output
            run: |
                bin/compare_correct.sh
