name: CCDA parsing with Spark
run-name: ${{ github.actor }} is doing a test run of the CCDA parsing
on: [push]
jobs:
    Run-main:
        runs-on: ubuntu-latest
        steps:
          - name: Check out repository code
            uses: actions/checkout@v4
            with:
              ref: spark
          - name: run main.py 
            run: |
                python3 main.py -n=2
    Lint-Flake8:
        runs-on: ubuntu-latest
        steps:
          - name: Install linters
            run: |
                pip install flake8
          - name: Check out repository code
            uses: actions/checkout@v4
            with:
              ref: spark
          - name: Lint with flake8
            run: |
                flake8 *.py --count --select=E9,F36,F92 --show-source --max-line-length=100 --statistics
                flake8 *.py  --count --max-complexity=10 --max-line-length=100 --statistics
    Lint-Pylint:
        runs-on: ubuntu-latest
        steps:
          - name: Install linters
            run: |
                pip install pylint
          - name: Check out repository code
            uses: actions/checkout@v4
            with:
              ref: spark
          - name: Lint with Pylint
            run: |
                pylint --max-locals=25  *.py

